language: php
php:
  - 7.4

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build_production
  repo: $GITHUB_DEPLOY_REPO
  target_branch: static_site
  keep-history: true
  email: travis-ci@phpwomen.org.br
  name: Travis-CI
  fqdn: phpwomen.org.br
  on:
    branch: master

before_script:
  - npm install -g gulp

before_deploy:
  - composer install
  - composer prod

script: /bin/true
